spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB
server.port: 8081

mid:
  client:
    relyingPartyUuid: 00000000-0000-0000-0000-000000000000
    relyingPartyName: DEMO
    applicationProviderHost: https://tsp.demo.sk.ee/mid-api
  auth:
    displayText: Log in with MID demo?
    displayTextFormat: GSM7
    displayTextLanguage: ENG
  sign:
    displayText: Подписать?
    displayTextFormat: UCS2
    displayTextLanguage: RUS
  truststore:
    trusted-server-ssl-certs:
      filename: classpath:/mid.test_trusted_server_certs.p12
      password: changeme
    trusted-root-certs:
      filename: classpath:/mid.test_trusted_root_certs.p12
      password: changeit
